### ISSUE TITLE
English support

### ISSUE THREAD

**Issue by asterriya** [lixiang810/CloudflareSpeedTest-Rust#1]
Any plan to have English interface?

**Comment by lixiang810** [comment]
This project was originally written mainly for those living in mainland China, as they often do not have a good experience with websites that use Cloudflare. However, if, as you tell me in this issue, there are non-native speakers of Chinese among the users of this project, I will add English support.

**Comment by asterriya** [comment]
> This project was originally written mainly for those living in mainland China, as they often do not have a good experience with websites that use Cloudflare. However, if, as you tell me in this issue, there are non-native speakers of Chinese among the users of this project, I will add English support.

I'm talking about interface with English language. Not about GitHub page.

**Comment by lixiang810** [comment]
I know that, and I'm coding.

**Comment by lixiang810** [comment]
The latest version had added English support, you can get it here: https://github.com/lixiang810/CloudflareSpeedTest-Rust/releases
