### ISSUE TITLE
Is it possible to get the latest ip address range from cloudflare instead of the existing hardcoded pattern?

### ISSUE THREAD

**Issue by aa51513** [lixiang810/CloudflareSpeedTest-Rust#11]
Is it possible to get the latest ip address range from cloudflare instead of the existing hardcoded pattern?
是否可以从 cloudflare 获取最新的 IP 地址范围，而不是现有的硬编码模式？

Loaded from cloudflare via https request when the program starts, it can cope with changes well without modifying the source code
在程序启动的时候通过https请求从cloudflare加载，可以很好的应对变更，而不用修改源代码

Official IP address range release and update page address:
官方ip地址范围发布以及更新情况页面地址：
https://www.cloudflare.com/ips/

url for program fetch (newline delimited):
用于程序程序获取的url（换行符分隔）：
https://www.cloudflare.com/ips-v4
and  和
https://www.cloudflare.com/ips-v6

built-in IPs that have been removed can be eliminated based on the above
甚至都可以基于上述内容，剔除掉已经被移除的内置IP

**Comment by lixiang810** [comment]
如果你实际使用过，你应该知道这个项目从第一版开始就有这个功能。

**Comment by lixiang810** [comment]
![54940E07-1872-472B-B64A-189345DCB910](https://user-images.githubusercontent.com/14120445/199656392-c614727c-5023-43be-9827-0c4ebba7f770.jpeg)

相关代码参见：https://github.com/lixiang810/CloudflareSpeedTest-Rust/blob/main/src/utils/get_all_ips.rs#L57

也许是我表达能力有限，没说明得足够好吧。

**Comment by aa51513** [comment]
> ![54940E07-1872-472B-B64A-189345DCB910](https://user-images.githubusercontent.com/14120445/199656392-c614727c-5023-43be-9827-0c4ebba7f770.jpeg)
> 
> 相关代码参见：https://github.com/lixiang810/CloudflareSpeedTest-Rust/blob/main/src/utils/get_all_ips.rs#L57
> 
> 也许是我表达能力有限，没说明得足够好吧。

I'm so sorry, I only realized after reading the code that I misunderstood, I really like your work
非常抱歉，我看完代码后才明白是我误解了，我非常喜欢您的作品
