### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by fengguowudi** [lixiang810/CloudflareSpeedTest-Rust#14]
[1]    158534 segmentation fault (core dumped)

建议架构切换为 gnu

同时增加更多cpu支持 例如32位 arm64

**Comment by fengguowudi** [comment]
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `quote` due to previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `proc-macro2` due to previous error

**Comment by lixiang810** [comment]
把 `gcc` 装一下，还有 `clang`

**Comment by fengguowudi** [comment]
https://paste.wmlabs.net/raw/84a7fea48658

**Comment by fengguowudi** [comment]
log

**Comment by lixiang810** [comment]
![图片](https://user-images.githubusercontent.com/14120445/204090292-3d5102ca-8967-4f64-a2b1-579fdb147846.png)
装 `pkg-config`

**Comment by fengguowudi** [comment]
https://pastebin.com/yj1Biy4U

**Comment by fengguowudi** [comment]
log

**Comment by lixiang810** [comment]
装 `openssl`

**Comment by fengguowudi** [comment]
已经存在的。。。

**Comment by fengguowudi** [comment]
![image](https://user-images.githubusercontent.com/55879152/204090528-d98d1bd4-f428-41b4-ae9e-8594421711ff.png)

**Comment by lixiang810** [comment]
`openssl-dev` 或者 `openssl-devel`

**Comment by fengguowudi** [comment]
![image](https://user-images.githubusercontent.com/55879152/204090573-1f182d76-4536-4c83-9cdf-08b13e6554ce.png)

**Comment by lixiang810** [comment]
![图片](https://user-images.githubusercontent.com/14120445/204090578-c816f32c-3417-48c1-bc5e-f3f8c87a661f.png)

`libssl-dev`

**Comment by fengguowudi** [comment]
https://pastebin.com/a9P9JkUY

**Comment by lixiang810** [comment]
你 rustup 装的是 stable 还是 nightly？

**Comment by fengguowudi** [comment]
curl https://sh.rustup.rs -sSf | sh rustup-init

**Comment by lixiang810** [comment]
https://github.com/lixiang810/CloudflareSpeedTest-Rust/blob/main/Cargo.toml#L10

这一行改成

`tokio = { version = "1.20.1", features = ["full"] }`

**Comment by fengguowudi** [comment]
好了）））感谢
