### ISSUE TITLE
Cutom IP's

### ISSUE THREAD

**Issue by asterriya** [lixiang810/CloudflareSpeedTest-Rust#2]
Please add option for custom IP's from CF. I have a big list of them and want to try by myself.

**Comment by lixiang810** [comment]
Feature added. By the way, don't forget to star this repo.

**Comment by asterriya** [comment]
But how to use it? It's not working for me. Created shortcut of cfst.exe with the next parameter  -c ip.txt. And уму try to create full path. And no result because window start to closed immediately.

**Comment by lixiang810** [comment]
Try to call it in cmd and get the output.

**Comment by asterriya** [comment]
> Try to call it in cmd and get the output.

but how to do that?

**Comment by lixiang810** [comment]
Suppose that you're using Windows10+:
1. Right click the start button, open `Windows PowerShell` or `Windows Terminal`.
2. Type `cd <ROUTE_TO_CFST.EXE>` and press enter. For example, for `C:\Users\abcde\Desktop\cfst.exe` type `cd C:\Users\abcde\Desktop`.
3. Type `cfst.exe -c ip.txt`. (Suppose the `ip.txt` is in the same folder with `cfst.exe`)

**Comment by asterriya** [comment]
https://www.upload.ee/image/14127792/issue.jpg

**Comment by asterriya** [comment]
> After `cd D:\`, you should type `D:` and press Enter, because it's another disk.

Yes, I know. But still same error.

**Comment by asterriya** [comment]
I'm using Win7x64

**Comment by asterriya** [comment]
ip.txt placed the same folder as it should be.

<img src="https://www.upload.ee/image/14127919/issue.jpg" border="0" alt="issue.jpg" />

**Comment by lixiang810** [comment]
In your situation, you should try `D:\CF-Rust\cfst.exe -c D:\CF-Rust\ip.txt` because you're in `D:\`, not `D:\CF-Rust`. Or you can try `cd CF-Rust` and `.\cfst.exe -c .\ip.txt`.

**Comment by asterriya** [comment]
Same error. Nothing works with those variants. Seems like it was bad idea.

**Comment by lixiang810** [comment]
![图片](https://user-images.githubusercontent.com/14120445/167633158-f77d95d9-6d03-4418-8597-8b8147f75144.png)

Cannot reproduce in Windows 11 and I don't know how to fix it.

**Comment by lixiang810** [comment]
You can try https://github.com/XIU2/CloudflareSpeedTest but it don't have i18n support.

**Comment by asterriya** [comment]
> You can try https://github.com/XIU2/CloudflareSpeedTest but it don't have i18n support.

Yes, I know about this project. But your's showing more accurate metrics. That's why I was interested.
