### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by delphinuz** [lixiang810/CloudflareSpeedTest-Rust#3]
可以出个ipv6版本吗？

可以帮忙测试，谢谢。

**Comment by lixiang810** [comment]
我已经有 ipv6 环境了，可以写一个

**Comment by lixiang810** [comment]
由于以下原因，该 issue 暂时 pending：

1. Cloudflare 官方给出的 IPv6 IP 列表不全是可用的（事实上很大一部分都不可用）。
2. 我暂时无法让程序在满足“只与 Cloudflare 服务器进行通信”的前提下获取一份可用率高的 IP 列表。

如确有需要，可以试试拿 Go 写的 Cloudflare IP 测试，这个项目有一份可用的列表： https://github.com/XIU2/CloudflareSpeedTest

**Comment by lixiang810** [comment]
由于上游原因 https://github.com/kolapapa/surge-ping/issues/19，我的程序没法 ping 通任何 IPv6 的 IP，上游修复后我可以更新。
IPv6 有关的需求可暂时以 https://github.com/XIU2/CloudflareSpeedTest 替代。

**Comment by kolapapa** [comment]
> 由于上游原因 [kolapapa/surge-ping#19](https://github.com/kolapapa/surge-ping/issues/19) ，我的程序没法 ping 通任何 IPv6 的 IP，上游修复后我可以更新。 IPv6 有关的需求可暂时以 https://github.com/XIU2/CloudflareSpeedTest 替代。

可以再试试看嘛？ 刚刚发布了`0.5.3`，我本地测试ipv6 ping应该是可以通过了

**Comment by lixiang810** [comment]
@kolapapa 试了一下，发现 example 没问题，但我这里还是有问题，很奇怪。报的是 `io error`，你需要我的复现代码吗？我可以开个 branch 丢进去

**Comment by kolapapa** [comment]
> 

有demo吗？我试试

**Comment by kolapapa** [comment]
> @kolapapa 试了一下，发现 example 没问题，但我这里还是有问题，很奇怪。报的是 `io error`，你需要我的复现代码吗？我可以开个 branch 丢进去

有demo吗？

**Comment by lixiang810** [comment]
@kolapapa 本项目的 test branch 下有未完工（ipv6 IP 随机生成部分是一个不完善的方案）的代码。

可以通过 `cargo run -- -c ip.txt` 的方式运行，之后在模式中选择 `IPv6`，其中 `ip.txt` 的内容如下，需要自行新建：

```plaintext
2606:4700:3000::/48
2606:4700:3001::/48
2606:4700:3002::/48
2606:4700:3003::/48
2606:4700:3004::/48
2606:4700:3005::/48
2606:4700:3006::/48
2606:4700:3007::/48
2606:4700:3008::/48
2606:4700:3009::/48
2606:4700:3010::/48
2606:4700:3011::/48
2606:4700:3012::/48
2606:4700:3013::/48
2606:4700:3014::/48
2606:4700:3015::/48
2606:4700:3016::/48
2606:4700:3017::/48
2606:4700:3018::/48
2606:4700:3019::/48
2606:4700:3020::/48
2606:4700:3021::/48
2606:4700:3022::/48
2606:4700:3023::/48
2606:4700:3024::/48
2606:4700:3025::/48
2606:4700:3026::/48
2606:4700:3027::/48
2606:4700:3028::/48
2606:4700:3029::/48
2606:4700:3030::/48
2606:4700:3031::/48
2606:4700:3032::/48
2606:4700:3033::/48
2606:4700:3034::/48
2606:4700:3035::/48
2606:4700:3036::/48
2606:4700:3037::/48
2606:4700:3038::/48
2606:4700:3039::/48
```

**Comment by kolapapa** [comment]
另外，surge-ping 的这个错误信息 io error 错误信息有点少，我再升级一个小版。

**Comment by lixiang810** [comment]
@kolapapa 感谢帮助，现在这里可以正常运行了。

**Comment by lixiang810** [comment]
2.0.0 已支持 IPv6。

**Comment by lixiang810** [comment]
似乎因为 surge_ping 把 0.5.3 删了，构建失败。一会儿再说

**Comment by lixiang810** [comment]
2.0.1 已发布
