### ISSUE TITLE
IP list integration

### ISSUE THREAD

**Issue by asterriya** [lixiang810/CloudflareSpeedTest-Rust#4]
Hi, I want to send to you directly (to your e-mail) full list of Cloudflare IP's that I found but don't want to share it here.

My idea is to integrate those full IP list into your app without asking it from external server. Yes, I understand that Cloudflare updating their IP network, but it happens so rare.

**Comment by lixiang810** [comment]
OK. You can send it here: `lixiang3@outlook.com`
