### ISSUE TITLE
Android Termux

### ISSUE THREAD

**Issue by t-e-s-tweb** [lixiang810/CloudflareSpeedTest-Rust#5]
Is there anyway to run it in termux? I have downloaded linux cfst and installed rust but running it with ./cfst gives error bash ./cfst bad adress.

**Comment by lixiang810** [comment]
What's your arch? Is it ARM? If it's not x86_64, you should [compile cfst yourself](https://github.com/lixiang810/CloudflareSpeedTest-Rust/blob/main/README-en_US.md#-build-it-yourself).
