### ISSUE TITLE
使用自定义ip报错如下

### ISSUE THREAD

**Issue by fengguowudi** [lixiang810/CloudflareSpeedTest-Rust#6]
`thread 'main' panicked at 'called Result::unwrap() on an Err value: AddrParseError(())', src/utils/get_all_ips.rs:92:77
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`

**Comment by lixiang810** [comment]
基本可以认为是文件换行符问题。该问题可以通过将自定义 ip 文件中的换行符从 CRLF 修改为 LF 来解决，目前已知的编辑器中 VSCode 可以这么做。修复后的版本会很快发布，在此之前请试着用上面的办法来解决。

**Comment by fengguowudi** [comment]
已经更改为lf编码

**Comment by lixiang810** [comment]
你地址咋写的，发出来看一下（不想把你的ip列表完整发上来的话可以把ip改几个数字，或者发部分的）

**Comment by fengguowudi** [comment]
*.184.*.0/254

**Comment by fengguowudi** [comment]
211.148.23.218
23.205.114.226
23.201.40.226
23.52.64.226
23.217.206.226
125.56.185.226
125.56.186.226
184.87.174.226
104.121.65.226
2.18.64.226
23.210.192.226

**Comment by lixiang810** [comment]
> *.184.0.0/254

这个不行，因为：

1. 不支持通配符。
2. ipv4 总共就 32 个 bit，已知 /16 是前 16 个 bit 不变的意思，求：/254 是啥意思？

正确的格式请参考：https://github.com/XIU2/CloudflareSpeedTest/blob/master/ip.txt 我这个项目使用的自定义 ip 文件格式和这个完全一致

**Comment by fengguowudi** [comment]
> > *.184.0.0/254
> 
> 这个不行，因为：
> 
> 1. 不支持通配符。
> 2. ipv4 总共就 32 个 bit，已知 /16 是前 16 个 bit 不变的意思，求：/254 是啥意思？
> 
> 正确的格式请参考：https://github.com/XIU2/CloudflareSpeedTest/blob/master/ip.txt 我这个项目使用的自定义 ip 文件格式和这个完全一致

那个*号是为了隐藏

**Comment by lixiang810** [comment]
> 那个*号是为了隐藏

OK，总之 ipv4 的地址那个斜杠后面只能 0-32，你需要先搞明白这个 ip 地址段的表示法。

**Comment by fengguowudi** [comment]
> > 那个*号是为了隐藏
> 
> OK，总之 ipv4 的地址那个斜杠后面只能 0-32，你需要先搞明白这个 ip 地址段的表示法。

嗯，我知道了，那我还发了一个纯ip的列表，这个也无法运行

**Comment by fengguowudi** [comment]
211.148.23.218
23.205.114.226
23.201.40.226
23.52.64.226
23.217.206.226
125.56.185.226
125.56.186.226
184.87.174.226
104.121.65.226
2.18.64.226
23.210.192.226

**Comment by fengguowudi** [comment]
`遮盖.184.44.0/23`

这种写法运行之后会变成这样
`请输入·测试轮数 (0 ≤ x ≤ 0) (每轮 4096 个，用时 10 秒，互不重复) [1]:`

**Comment by lixiang810** [comment]
> `遮盖.184.44.0/23`

这个是唯一正确的 ip 段表示法，前面只给纯 ip 是不行的。测试轮数为 0 的问题我再看看

**Comment by fengguowudi** [comment]
> > `遮盖.184.44.0/23`
> 
> 这个是唯一正确的 ip 段表示法，前面只给纯 ip 是不行的。测试轮数为 0 的问题我再看看

那是否能支持下ip列表（ 我希望还有些ip可以测试

**Comment by lixiang810** [comment]
> 那是否能支持下ip列表

[最新版本](https://github.com/lixiang810/CloudflareSpeedTest-Rust/releases/tag/v2.2.0)已支持 ip 列表（可与 ip 段列表混在一起），同时解决了测试轮数为 0 的问题
