### ISSUE TITLE
有的时候测速不显示结果

### ISSUE THREAD

**Issue by fengguowudi** [lixiang810/CloudflareSpeedTest-Rust#8]
`Error: reqwest::Error { kind: Body, source: hyper::Error(Body, Custom { kind: UnexpectedEof, error: "unexpected EOF during chunk size line" }) }`

报错是这个

**Comment by fengguowudi** [comment]
再次出现

**Comment by fengguowudi** [comment]
将对 10 个 ip 进行下载速度测试
正在测试：47.243.146.249
正在测试：111.161.121.75
正在测试：47.242.193.142
正在测试：47.242.254.50
正在测试：8.218.57.225
正在测试：47.243.74.153
正在测试：146.56.186.202
正在测试：146.56.130.242
正在测试：35.241.72.154
Error: reqwest::Error { kind: Body, source: hyper::Error(Body, Custom { kind: UnexpectedEof, error: "unexpected EOF during chunk size line" }) }

**Comment by fengguowudi** [comment]
请问找到问题所在了吗？

**Comment by lixiang810** [comment]
试试[这个](https://github.com/lixiang810/CloudflareSpeedTest-Rust/releases/tag/v2.2.2)
